architecture: resnet18
dataset: shapenet
encoder_path_resnet: ./pretrained_models/simpleshot/shapenet/shape-biased-w-pc/joint-shapenet-pairwise-simpleshot-w-pc/version_0/checkpoints/epoch=364_val_acc=0.680.ckpt 
exp_name: shapenet-joint-feat-5-shot-10-way-resnet18_wo_pc
feat_dict_file: dgcnn_ptcld_feat_dict.npz
log_dir: shapenet-feat-logs
ls_test_hparams:
  n_ls_test_iters: 5000
  n_ls_test_queries: 15
  n_ls_test_shots:
  - 5
  n_ls_test_ways:
  - 10
  - 20
  val_metric: euclidean
ls_val_hparams:
  n_ls_val_iters: 200
  n_ls_val_queries: 15
  n_ls_val_shots: 5
  n_ls_val_ways: 10
modality: image+shape_embedding
model_type: JointFEATClassifier
num_workers: 10
temperature1: 64.0
temperature2: 32.0
train_hparams:
  balance: 0.1
  gpus: 1
  learning_rate: 0.0002
  lr_gamma: 0.5
  lr_multiplier: 10
  max_epochs: 200
  n_ls_train_iters: 100
  n_ls_train_queries: 15
  n_ls_train_shots: 5
  n_ls_train_ways: 10
  step: 40
  train_metric: euclidean
  use_train_sampler: false
  val_freq: 1
  weight_decay: 0.0005
use_aug: true
use_euclidean: true
use_pc_for_lowshot: false
use_seed: false
